# Generated by Django 4.2.13 on 2024-05-07 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0004_sitesetup_favicon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesetup',
            name='favicon',
        ),
    ]
