# Generated by Django 4.2.13 on 2024-05-10 12:58

from django.db import migrations, models
import utils.model_validations


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0006_sitesetup_favicon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetup',
            name='favicon',
            field=models.ImageField(blank=True, default='', upload_to='assets/favicon/%Y/%m/', validators=[utils.model_validations.validate_png]),
        ),
    ]
