# Generated by Django 5.0.4 on 2024-05-13 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category_page_remove_tag_nome_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Este campo precisará estar marcadopara a página ser exibida publicamente.'),
        ),
    ]
